version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Shorten.Redirect/Dockerfile.txt
    ports:
      - '8080:8080'
    environment:
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
